@localhost=localhost:4004/odata/v4/main
@id=c4b0f1b9-4c40-4f8a-90b8-f886e119f140
@customerId=17048929-deeb-44ec-8e54-4f9acc1662ae
# produto sem estoque
@productId1=23415777-06e9-40a1-82b2-ebb421433368
@productId2=23415780-c79d-4dd7-8593-4eed8a3b098d

POST http://{{localhost}}/bulkCreateSalesOrders
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345

{
    "payload": [
        {
            "id": "{{id}}",
            "customer_id": "15835084-bccf-49e8-9465-9d70bdee3e7d",
            "items": [
                {
                    "id": "c23ccfc1-2d10-4274-8e1c-6aa7d95e0300",
                    "header_id": "{{id}}",
                    "product_id": "{{productId2}}",
                    "quantity": 10,
                    "price": 2.99
                },
                {
                    "id": "1463f1d6-4c71-4822-9497-86ede7ba9f2b",
                    "header_id": "{{id}}",
                    "product_id": "{{productId2}}",
                    "quantity": 5,
                    "price": 1.99
                }
            ]
        },
        {
            "id": "{{id}}",
            "customer_id": "15835084-bccf-49e8-9465-9d70bdee3e7d",
            "items": [
                {
                    "id": "c23ccfc1-2d10-4274-8e1c-6aa7d95e0301",
                    "header_id": "{{id}}",
                    "product_id": "{{productId2}}",
                    "quantity": 100,
                    "price": 2.99
                }
            ]
        }
    ]
}