@localhost=localhost:4004/odata/v4/main

@id=2baa7beb-555e-40eb-bb77-9562caf50ce4

GET http://{{localhost}}/Products
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345

###

POST http://{{localhost}}/Products
Content-Type: application/json
Authorization: Basic cuka:Inicial@12345

{
  "id": "{{id}}",
  "name": "Produto 01",
  "price": 1.99
}

###

DELETE http://{{localhost}}/Products(id={{id}})
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

###

PUT http://{{localhost}}/Products(id={{id}})
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

{
    "price": 2.99
}

###

PATCH http://{{localhost}}/Products(id={{id}})
Content-Type: application/json
Authorization: Basic joaozinho:Inicial@12345

{
    "price": 3.99
}