
@localhost=localhost:4004/odata/v4/main

@id=483f2adb-57db-4a2e-b635-b81ac479d044

@customerId=f15c3f6e-c6f0-4ad0-8f5d-acae11c9a2fe

@productId=2baa7beb-555e-40eb-bb77-9562caf50ce4

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json

{
    "id": "{{id}}",
    "customer_id": "{{customerId}}",
    "totalAmount": 39.85,
    "items": [
        {
            "id": "c004be3a-c1e7-4a65-a1ff-62d3b5f846a5",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "be18307b-c7c3-446a-bd28-ef400ff7d4fa",
            "header_id": "{{id}}",
            "product_id": "{{productId}}",
            "quantity": 5,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json

{
    "modifiedBy": "cris"
}

###

GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 4599898060056
Content-Type: application/json


###

### Expandindo os items
GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq 483f2adb-57db-4a2e-b635-b81ac479d044 &$expand=items($expand=product;$filter=quantity ge 6), customer
Content-Type: application/json

###

### Selecionar somente customer e id do sales order header
GET http://{{localhost}}/SalesOrderHeaders?$select=id&$expand=customer($select=id,firstName)
Content-Type: application/json

###

### Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json


###

### Paginando os registros
GET http://{{localhost}}/SalesOrderHeaders?$skip=2&$top=3
Content-Type: application/json